line-length = 120
indent-width = 2
preview = true

target-version = "py310"

[lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "N",
    "D",
    "UP",
    "YTT",
    "ANN",
    "ASYNC",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "EM",
    "EXE",
    "FA",
    "ISC",
    "LOG",
    "G",
    "PIE",
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SIM",
    "TCH",
    "ARG",
    "PTH",
    "TD",
    "PD",
    "PGH",
    "PLE",
    "PLW",
    "PLC",
    "PLR01",
    "PLR02",
    "PLR04",
    "PLR1",
    "PLR2",
    "PLR5",
    "PLR6",
    "TRY201",
    "TRY400",
    "FLY",
    "NPY",
    "PERF",
    "FURB",
    "DOC",
    "RUF",
]
ignore = ["D100", "E111", "E114"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.pydocstyle]
convention = "numpy"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
